M48
; DRILL file {KiCad 6.0.3-a3aad9c10e~116~ubuntu20.04.1} date Sun 20 Mar 2022 09:21:37 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-20T21:21:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.3-a3aad9c10e~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1600
%
G90
G05
T1
X-0.15Y1.29
X-0.15Y-0.99
X1.79Y1.29
X1.79Y-0.99
T2
X-2.25Y0.0675
T3
X-2.425Y-1.775
X-2.225Y-1.775
X-0.72Y-1.7643
X-0.52Y-1.7643
T4
X-2.3535Y3.07
X-1.4445Y3.07
T0
M30
