M48
; DRILL file {KiCad 6.0.3-a3aad9c10e~116~ubuntu20.04.1} date Mon 21 Mar 2022 01:13:55 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-21T01:13:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.3-a3aad9c10e~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1500
%
G90
G05
T1
X0.55Y0.1
X0.6Y2.0
X2.6Y1.4
X2.6Y0.3
T2
X0.69Y0.8241
T3
X0.0857Y0.76
X0.0857Y0.56
T0
M30
