M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date Sat 29 Jan 2022 07:32:40 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-29T19:32:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1600
%
G90
G05
T1
X4.85Y-4.8
X4.9Y-2.9
X6.9Y-3.5
X6.9Y-4.6
T2
X6.379Y-3.0891
T3
X4.5482Y-3.345
X4.5482Y-4.254
T0
M30
